FROM php:8.2-apache

# Install MySQL client and extensions
RUN apt-get update && apt-get install -y \
    default-mysql-client \
    libmariadb-dev-compat \
    libmariadb-dev \
    && docker-php-ext-install mysqli pdo pdo_mysql \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./www /var/www/html/
COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 80
EXPOSE 3306

# Enable mod_rewrite if needed
RUN a2enmod rewrite