FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

# Clone SpiderFoot officiel
RUN git clone https://github.com/smicallef/spiderfoot.git /app

WORKDIR /app

# Install dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Entrypoint stable
ENTRYPOINT ["python", "sf.py"]